### ISSUE TITLE
Web Search: "SearchAll" should be replaced by "Search Selected"

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10556]
## Background

Current of the web search:

![current-web-search](https://github.com/koppor/jabref/assets/1366654/d9d6ed2b-3f28-423a-b8bc-f1ccbd4170ec)

In the SLR feature, we offer a selection mode of selecting libraries to the SLR feature. This feature should be re-used in this form.

![slr](https://github.com/koppor/jabref/assets/1366654/09d41e34-d3fa-44ed-ac10-59f1d6ecfc4e)

The SLR can be started at

![image](https://github.com/JabRef/jabref/assets/1366654/bfc95f19-4866-4df6-acc4-1271b82963a8)

## Tasks

- [ ] Implement "Search Selected". Inspiration by the "SearchAll" functionality.
- [ ] Enable configuring the catalogs to be searched. Should be done in Preferences / Web Search (refs https://github.com/JabRef/jabref-issue-melting-pot/issues/140). Heading `Catalogues used for "Search Selected"`.
    ![new](https://github.com/koppor/jabref/assets/1366654/963fd6dc-adae-4d4e-af90-b25d024a3fd8)
- [ ] In the menu: Rename "SearchAll" to "Search Selected" (think, this is done by deleting SearchAll classes and references and inserting the reference to the Search Selected funtionality)
- [ ] Position "Search Selected" at the beginning of the drop down
- [ ] Ensure that in the UI, "catalogs" is used as term. Not "libraries", "web resources", ...

**Comment by lisongxuan** [comment]
Hello, I am interested in working on this issue. Could you assign it to me? Thank you.
