### ISSUE TITLE
Allow file attachment into the comments editor (Markdown)

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10559]
#### How to reproduce
1. Create a library with the file directory is `.`
2. Firefox: Visit https://www.sequoiacap.com/article/ai-powered-developer-tools/
3. Firefox: Import into JabRef
4. Go to the tab "Comments"
5. From Firefox: drag'n'drop the image onto the comment field

#### Expectation: 
1. `![](dev-ai-wide-10.png)` appears in the editor 
2. `dev-ai-wide-10.png` exists next to the `.bib` file (which is the file directory configured for the bib file)

#### Actual behavior
   File is attached

#### Additional Info
Note: Deep link to the image: https://www.sequoiacap.com/wp-content/uploads/sites/6/2023/03/dev-ai-wide-10.png?resize=1440,1400

#### TODOs

- [ ] 1. Use JabRef's download functionality
- [ ] 2. Add link into comment field (next to cursor)
- [ ] 3. Change "Find unlinked files" to ignore files linked in the comment fields

#### Background:

- Feature in VS.Code: https://code.visualstudio.com/updates/v1_79#_editor

**Comment by DavidCoy77** [comment]
Hello, I'm an undergraduate programming major that's eager to make my first GitHub contribution. Would I be able to claim this issue? Thanks!

**Comment by DavidCoy77** [comment]
I'm thoroughly occupied with the other issue I claimed (#10558), so I "unassigned" myself on this one. I'm not going to work on it at all, so it is completely free for someone else to claim.

**Comment by fyssgo** [comment]
Hi, I'm  looking for an issue for my project. Would you mind assigning this issue to me? I will try to fix it. Thanks!

**Comment by ThiloteE** [comment]
@weronikaulbricht Since there has not been any activity, I assume you have given up on this project, therefore will unassign you. If you are still on it, just leave a message.

**Comment by abimael-turing** [comment]
@ThiloteE If you would like, you can assign this issue to me!

**Comment by ThiloteE** [comment]
I already assigned you to another good first issue. Are you sure? Don't overload yourself.

**Comment by ADm1n766** [comment]
Hey, I'm looking for a good first issue and want to work at this one. I already have installed the jabref-Program working on intellij. Currently I try to reproduce the issue and need more information about the guideline.

At first what is important about the file directory, named: "."?

> #### How to reproduce
> 1. Create a library with the file directory is `.`
> 2. Firefox: Visit https://www.sequoiacap.com/article/ai-powered-developer-tools/
> 3. Firefox: Import into JabRef
> ...

**Comment by Siedlerchr** [comment]
@ADm1n766  create a new library in JabRef , then right click on the library properties -> General file directory  set to "."
this means it will take the relative path of the library, the location of the .bib file

**Comment by ADm1n766** [comment]
Probably I've reproduced the Issue completely:
At first I created a new library, then put some information in required fields from the website and copied the image "03/dev-ai-wide-10.png?w=1024" and if I have a connection to a network the image is displayed.

But if I want to put the image per drag and drop from the website without saving in a file directory I get the exception:

`Uncaught exception occurred in Thread[#53, JavaFX Application Thread, 5, main]
ReferenceError: Can´t find variable: Mark`

and much more detailed information. Thats the issue right?

**Comment by Siedlerchr** [comment]
@ADm1n766 Would be great if you could post the whole stackrace and if you have some local stuff already then go create a PR. Without seeing any code or the complete stacktrace  it's hard to identify the root cause

**Comment by ADm1n766** [comment]
Of course, with pleasure! Here is a screenshot from my exception:
![Issue-10559](https://github.com/JabRef/jabref/assets/89748226/ebd010f7-ce32-4479-80eb-b48da3c78696)

I hope the screenshot is displayed correctly.


ReferenceError: Can´t find the variable: Mark
**The whole exception stacktrace was**:
`netscape.javascript.JSException: ReferenceError: Can't find variable: Mark
	at javafx.web@22.0.1/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:160)
	at javafx.web@22.0.1/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at javafx.web@22.0.1/com.sun.webkit.WebPage.executeScript(WebPage.java:1576)
	at javafx.web@22.0.1/javafx.scene.web.WebEngine.executeScript(WebEngine.java:985)
	at org.jabref@100.0.0/org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(PreviewViewer.java:211)
	at org.jabref@100.0.0/org.jabref.gui.preview.PreviewViewer.lambda$new$2(PreviewViewer.java:176)
	at javafx.base@22.0.1/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:192)
	at javafx.base@22.0.1/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:91)
	at javafx.base@22.0.1/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:80)
	at javafx.base@22.0.1/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.base@22.0.1/javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:113)
	at javafx.base@22.0.1/javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
	at javafx.web@22.0.1/javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1264)
	at javafx.web@22.0.1/javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1379)
	at javafx.web@22.0.1/javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1244)
	at javafx.web@22.0.1/com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2577)
	at javafx.web@22.0.1/com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2421)
	at javafx.web@22.0.1/com.sun.webkit.network.URLLoaderBase.twkDidFinishLoading(Native Method)
	at javafx.web@22.0.1/com.sun.webkit.network.HTTP2Loader.notifyDidFinishLoading(HTTP2Loader.java:566)
	at javafx.web@22.0.1/com.sun.webkit.network.HTTP2Loader.lambda$callBackIfNotCanceled$10(HTTP2Loader.java:429)
	at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at javafx.graphics@22.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
	at javafx.graphics@22.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at javafx.graphics@22.0.1/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@22.0.1/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:1583)
`

**Comment by Siedlerchr** [comment]
Ah interesting, that is coming from the javascript that is used for the search highlighting:

>  at org.jabref@100.0.0/org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(PreviewViewer.java:211)

**Comment by koppor** [comment]
The issue at hand is about the Markdown editor (!) , not the preview. 

As picture:

![image](https://github.com/JabRef/jabref/assets/1366654/4356060c-d7f7-4941-b813-0f2bb33f975a)

Please try to focus on that and not to find other issues.

The class to modify should be https://github.com/JabRef/jabref/blob/f570a2d9157f9667bc84a1c2e4e6a4f15d999ca5/src/main/java/org/jabref/gui/fieldeditors/MarkdownEditor.java#L15.

Note for developers: The preview is discussed in an internal issue https://github.com/JabRef/jabref-issue-melting-pot/issues/452.

**Comment by JorECardenas** [comment]
Hello I've been looking for a good first issue and I would like to implement this one. I just wanted to ask for more information on how to reproduce the issue:
- Like the way you can add an image from the website, is this done with the extension or you drag and drop from the web browser on to JabRef?
- Or does this issue apply to when you copy and paste an image from a website or also from the file explorer?

**Comment by ThiloteE** [comment]
I think it is copy and paste.

**Comment by JorECardenas** [comment]
Hi, I've been working for a bit on this issue and I managed to add the functionalities to drag-and-drop and also copy-paste images on the markdown editor and insert the text in the ![]() format, the next challenge is that the way I found to access files is by using "file://" with the absolute path of the image so it ends up looking like this:

![Image](https://github.com/user-attachments/assets/6185fb6d-7f01-474a-97ac-1bde0307103d)

For the next part I'm planning to make it so that the markdown editor shows only the image name instead of the full path but then the preview adds the "file://" so it can access the image, there is also a few other details here that maybe aren't inside the scope of the issue but here they are:

- The images are shown with their actual size so they end up mostly looking too big for the preview pane
- I'm still not able to check if the image is on the default directory or able to move/copy images that aren't in this directory (for now I'm planning to at least check if the image is on the folder)

So it would help me if you could at least point me in the right direction so I can solve this in the best way possible

**Comment by koppor** [comment]
>     * Like the way you can add an image from the website, is this done with the extension or you drag and drop from the web browser on to JabRef?

See step 5 on the issue description: Drag'n'drop from web browser.

Additionally: drag''drop from the file system should also be possible.

When drag'n'drop of a file, the ususal file attachment handling should be made. (which moves the file if it is outside, the functionality is there)

Moreover, I think, it would be good if drag'n'drop from firefox, the file should also be linked. Then, one does not have issues at find-unlinked-files.

>     * Or does this issue apply to when you copy and paste an image from a website

This is an additional wish, you can also implement that.

>     *  or also from the file explorer?

This is an additional wish, you can also implement that.

**Comment by koppor** [comment]
> Hi, I've been working for a bit on this issue and I managed to add the functionalities to drag-and-drop and also copy-paste images on the markdown editor and insert the text in the format, 

Nice! You can open a PR if you want. It might be hard to discuss things with screenshots only.

> the next challenge is that the way I found to access files is by using "file://" with the absolute path of the image so it ends up looking like this:

`file://` is wrong. 

See how it works in markdown: https://github.com/JabRef/jabref/blob/main/README.md. Click on "Raw" and see 

    ![main table](docs/images/jabref-mainscreen.png)

no `file://`.

> For the next part I'm planning to make it so that the markdown editor shows only the image name instead of the full path 

The path needs to be relative. See also the handling of linked files. - Maybe, it is good to re-use the linked files functionality.

> but then the preview adds the "file://" so it can access the image, there is also a few other details here that maybe aren't inside the scope of the issue but here they are:
>
>    The images are shown with their actual size so they end up mostly looking too big for the preview pane

There is [Resizable Image Extension](https://github.com/vsch/flexmark-java/wiki/Extensions#resizable-image-extension)

>   I'm still not able to check if the image is on the default directory or able to move/copy images that aren't in this directory (for now I'm planning to at least check if the image is on the folder)

`org.jabref.logic.util.io.FileUtil#find(java.lang.String, java.util.List<java.nio.file.Path>)` is your friend here.

**Comment by ThiloteE** [comment]
@JorECardenas even if you have dropped this issue, opening a pull-request would be nice, since you say you have solved the issue at least partially. Other people might pick it up from there.

**Comment by JorECardenas** [comment]
Hi, I made the PR draft of my attempt to add this feature, I hope it is helpful to the next person that works on this issue

**Comment by koppor** [comment]
Example:

![Image](https://github.com/user-attachments/assets/b28232a6-4505-42e0-9168-df284545201a)

This shows that the "Comment" field supports markdown - and the rendering supports images (theoretically)

Images can also be displayed:

![Image](https://github.com/user-attachments/assets/d58d7f90-5685-49fd-9cd7-ac055ddcd196)

One neesd to investigate how local paths work in that markdown syntax.

One might need to resolve the relative paths to an aboslute one. 

```
                    LinkedFile fileName = files.get(j);
                    Optional<Path> path= fileName.findIn(databaseContext, preferences.getFilePreferences());
```

**Comment by viru0909-dev** [comment]
Hello maintainers,

Due to other commitments, I am no longer able to work on this issue or complete the associated pull request (#14183).

Could you please unassign me so another contributor can pick this up? Thank you!

**Comment by koppor** [comment]
@viru0909-dev Thank you for letting us know. Since we are also researching on contributors motivation, may you share what brought you to JabRef and why did you drop work directly after submitting a pull request? Is it Hacktoberfest?

**Comment by Hemant-web19** [comment]
"Hey, this is my first contribution. Could you please assign this issue to me?"

**Comment by Hemant-web19** [comment]
“Hi, I’d like to work on this issue, please assign me.”

**Comment by koppor** [comment]
@Hemant-web19 Your messages make the impression you are using AI to let do the work for you. Please use this project as a possibility to learn something about software engineering. In case you just want to get some credit points, please choose another repository.

**Comment by Hemant-web19** [comment]
I admitted that i used AI for communication only as english is not my native language and not to look unprofessional.deeply sorry will take care in future ..
