### ISSUE TITLE
Bring back content selectors

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10560]
### JabRef 3.8.2

JabRef 3.8.2 had the possibility to use pre-defined words for the keyword field. Instead of auto-completion, the user could use a drop down field:

![a](https://github.com/JabRef/jabref/assets/1366654/3891c49e-c696-4e49-acc9-7c7472219d12)

### JabRef 5.12

In today's JabRef, there is no such possibility:

![b](https://github.com/JabRef/jabref/assets/1366654/bc853cb9-0400-4b57-9d20-9949f2965df7)

One can still configure the list where the user can choose the available "keywords" to offer.

![c](https://github.com/JabRef/jabref/assets/1366654/8ac6933f-afca-4d2c-94aa-2621c6e7e7e5)

On the left, the field is selected, on the right, the possible contents are shown.

## Tasks

- [ ] Add the selection box next to the keyword field. The list should be filled with the contents of the content selectors list, minus the existing keywords.
   - This box is OUTSIDE the text box. It allows for selecting an item in a pre-defined list. Once a user clicks on the item, it is added alphabetically inside the list. In case the list is not alphabetically sorted, it is added to the end.
- [ ] In the configuration of the "Content Selectors", do NOT allow configuration of Fields having the property "`org.jabref.model.entry.field.FieldProperty#PERSON_NAMES`" (because there are soooo many authors, we think, it does not make sense to use it there)
- [ ] Change the popup to enter types to the combo box for custom entry types
   - old: ![d](https://github.com/JabRef/jabref/assets/1366654/8e62a42e-5dc7-4292-adcc-a229d9b58286)
   - new: ![e](https://github.com/JabRef/jabref/assets/1366654/df4f8fa1-fa1c-46fb-9993-da0c89ac0452)
- [ ] Optional: Rewrite the keyword edit to [tags](https://ux.stackexchange.com/a/85131/93436), [also called chips](https://ux.stackexchange.com/a/112668/93436)
  - Use GemFX Tags Field (https://github.com/dlsc-software-consulting-gmbh/GemsFX#tags-field)
  - An example is implemented at https://github.com/JabRef/jabref/pull/10046

**Comment by Rohxn16** [comment]
i would like to work on this issue

**Comment by Satya-Manikanta** [comment]
Hi @koppor 

In the `org.jabref.gui.entryeditor.*` folder, 
I found the files for Required fields, Optional fields, Comments as well (as you can see I modifiled the tab name with the integer)
but I am not able to locate the file for General tab.

Can you please provide the steps or instructions on how General tab is being rendered in the UI.
And from which file we are getting the data for General tab shown in screenshot.

![image](https://github.com/JabRef/jabref/assets/49039241/d8b9b2b3-8c74-4b56-a517-79c7db07b16e)

**Comment by koppor** [comment]
@Satya-Manikanta Understanding how the EntryEditor works is part of the levelling-up the code reading skills.

In `org.jabref.gui.entryeditor.EntryEditor#createTabs`, the routine **after** the "Comments" tab, there is the routine to fill the "General" tab. There, some magic is happening, because the content of that tab is configured in the preferences. The defaults are put at `org.jabref.preferences.JabRefPreferences#setLanguageDependentDefaultValues`.

**Comment by LoayGhreeb** [comment]
I would like to try to work on this issue.

@koppor, could you clarify how I can get the existing keywords to exclude them from the selection box? Should I split them by space, comma separator, or something else to be able to retrieve the words correctly?

**Comment by koppor** [comment]
@LoayGhreeb There is already an opened PR. Please do not work on this issue but choose another one.

**Comment by LoayGhreeb** [comment]
@koppor, the PR was opened by me

**Comment by koppor** [comment]
> I would like to try to work on this issue.
> 
> @koppor, could you clarify how I can get the existing keywords to exclude them from the selection box? Should I split them by space, comma separator, or something else to be able to retrieve the words correctly?

@LoayGhreeb Thank you for working on this. I didn't get that you are the one with the pull request. I will provide a more detailed answer later. I don't know all code by heart. One hint now: The separator is configured globally (called KeywordSeparator) and we have a class handling keywords (converting them to a list and back). Maybe you find it witj Ctrl+Shift+F.

**Comment by LoayGhreeb** [comment]
Hi @koppor, I have implemented most of the first task and the 3rd task is ready for review, I'm waiting for your feedback. 

I have a small question regarding the first task. Do you want to check if all keywords in the text field are ordered alphabetically so that the selected item should be placed in the correct order? Otherwise, it will be added to the end.

**Comment by koppor** [comment]
@LoayGhreeb Let JabRef be smart here. In case the list is ordered alphabetically, add it alphabetically. Else: Add it to the end. That way, JabRef is "smart" and does not change an existing order.

**Comment by LoayGhreeb** [comment]
> Let JabRef be smart here. In case the list is ordered alphabetically, add it alphabetically. Else: Add it to the end. That way, JabRef is "smart" and does not change an existing order.

Thanks for clarification @koppor, but since I will implement it using the `Tags Field` there is no need for this.

By the way, is this what is required in the second task?

https://github.com/JabRef/jabref/assets/52158423/beac062c-d0be-4dbd-bd09-4143c3bc9695

**Comment by koppor** [comment]
Regardingthe second task. A user can configure the content selectors for fields:

![image](https://github.com/JabRef/jabref/assets/1366654/3ac8d81c-7876-4e43-9521-6326f5bdb7b3)

My idea was to exclude field names which do not make sense to have content selectors. Not by name, but by property.

Maybe, it does not make sense. One would really need to think for which fields the content selectors would make sense. Much  more work. The proposal with avoiding "PERSON" was a gut thing. Not well-thought...

**Comment by koppor** [comment]
> but since I will implement it using the `Tags Field` there is no need for this.

I'm curious how this will be then... I hope, it won't resort the content. Let's see...
