### ISSUE TITLE
Switch to Apache Velocity for Custom Layouts

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#12418]
## Context

Our layout files are very strange. 

- Documentation: https://docs.jabref.org/import-export/export/customexports
- Repository for all layout files: https://github.com/JabRef/layouts.jabref.org
- Directory for all internal layout files: https://github.com/JabRef/jabref/tree/master/src/main/resources/resource/layout
- Example: HTML Export: https://github.com/JabRef/jabref/blob/master/src/main/resources/resource/layout/html.layout
- Example: Simple HTML: https://github.com/JabRef/jabref/blob/master/src/main/resources/resource/layout/simplehtml.layout
- Example: Simple Open Office Export: https://github.com/JabRef/jabref/tree/master/src/main/resources/resource/layout/openoffice

## Tasks

Steps:

1. Define new template format (based on Apache Velocity)
2. Implement a template for a simple example
3. Call the template in JabRef (includes JUnit test cases)
4. Iterate steps 1 to 3 until a "good" template language is there
5. Choose a larger example (e.g., convert BibTeX to JSON, manually port existing .layout files)

If possible:

1. Define a converter of existing `.layout` files to the new format (can be called via the command line)
2. Convert all existing layouts to the new format
3. Delete the old layout formats

### Variants

We could keep both the new engine and the old engine in JabRef and gradually migrate to the new one.

## Background/Links

ADR-039 result: use Velocity - see https://github.com/JabRef/jabref/blob/main/docs/decisions/0039-use-apache-velocity-as-template-engine.md

Check whether we could switch to some other export engine. Apache Velocity, yeoman-based, ...

See https://github.com/latextemplates/generator-latex-template/blob/master/docs/adr/0001-use-yeoman.md for options for template generators.

See https://github.com/latextemplates/generator-latex-template/blob/master/generators/app/templates/main.de.tex for the Yeoman syntax.

Refs https://github.com/xJREB/swe-research-methods/issues/1#issuecomment-579512077

---

Velocity was chosen at https://github.com/JabRef/jabref/pull/11900.

**Comment by koppor** [comment]
ADR on using velocity: https://github.com/JabRef/jabref/blob/main/docs/decisions/0039-use-apache-velocity-as-template-engine.md

**Comment by subhramit** [comment]
Based on a proposal we once received from a student:

## Rewriting the template & layout engine ([Thymeleaf](https://www.thymeleaf.org/))

### Problem

The current template engine is hand-crafted (`org.jabref.logic.layout.Layout` ~150 LOC, `LayoutHelper` ~400 LOC, `LayoutEntry` ~600 LOC, plus supporting classes). Its limitations:

- No conditional logic beyond checking whether a field exists
- No iteration - e.g. rendering keywords as a bullet list requires a dedicated Java formatter
- Formatters take a single `String` parameter, so they can't express relationships between fields (e.g. "show `comment` only if `abstract` is under 30 chars")
- [Custom formatters](https://docs.jabref.org/collaborative-work/export/customexports#custom-formatters) can only be written in Java, which pushes programming into what should be a non-programmer-friendly template format
- Layout resolution, formatter lookup, and reader handling are all done manually and aren't extensible
- Some exporters (e.g. `CffExporter`) are hard-coded and add hundreds of lines that a real template engine would absorb

### Proposal

Replace the bracketed-pattern engine with **Thymeleaf** in `TEXT` mode, plus a small custom dialect for JabRef-specific processors. This preserves existing functionality, removes a large amount of code, and adds conditionals, loops, and richer formatter customization.

Affected/enabled areas:

- [Custom export formats](https://docs.jabref.org/collaborative-work/export/customexports) (arbitrary output: JSON, YAML, Markdown, etc.)
- [Preview tab customization](https://docs.jabref.org/setup/preview#modification-of-the-customized-preview-style) (conditional fields, defaults derived from other fields)
- [OpenOffice/LibreOffice/MS Office style files](https://docs.jabref.org/cite/openofficeintegration#the-style-file)
- Hard-coded exporters (CFF and similar) collapse into templates
- New exporters become cheap to add - see [koppor/jabref#468](https://github.com/koppor/jabref/issues/468) (Markdown static bibliography page) and [koppor/jabref#684](https://github.com/koppor/jabref/issues/684) (academicpages.github.io)

### Engine choice

| Option | Pros | Cons |
|---|---|---|
| Apache Velocity | Simple, lightweight | Fewer capabilities out of the box (needs third-party components); templates end up calling Java object methods directly, which breaks the "non-programmer-friendly template" goal |
| Apache FreeMarker | Written for generic (non-web) use | Realistic use cases tend toward complex templating workflows ([source](https://stackoverflow.com/a/1984458/873282)) |
| **Thymeleaf** | Natural templating for HTML; `TEXT` mode covers non-web templates; actively maintained; extensive docs; highly customizable | - |

**Chosen: Thymeleaf** - standard framework, capabilities go well beyond the alternatives without much boilerplate.

### Work items

**1. Define the template format**

- [ ] Define a base template format using the [Thymeleaf Standard Dialect](https://www.thymeleaf.org/doc/articles/standarddialect5minutes.html); validate against simple examples and iterate
- [ ] Add a [custom dialect with new processors](https://www.thymeleaf.org/doc/articles/sayhelloextendingthymeleaf5minutes.html) covering two features of the current bracketed-pattern engine
- [ ] Port larger examples by hand (e.g. BibTeX → JSON) to stress-test the format
- [ ] Extend the custom dialect to cover *all* remaining features of the current engine (conditional/grouped output, merging `*.begin.layout` / `*.layout` / `*.end.layout` into a single file, etc.)
- [ ] Port all existing formatters to the new format
- [ ] Add the new capabilities: iteration, formatter customization, advanced conditional logic

**2. Migration of existing layouts**

- [ ] Write an automated converter for old `*.layout` files, invokable via CLI
- [ ] Convert all bundled `*.layout` files and verify integrity
- [ ] Produce a mapping table (old syntax → new syntax) plus rows for the new features

**3. Codebase integration**

- [ ] Rewrite `logic.exporter.TemplateExporter`
- [ ] Rewrite OpenOffice/LibreOffice integration (`logic.openoffice.style`)
- [ ] Rewrite custom preview (`gui.preview`)
- [ ] Rewrite the citation key generator to use the new formatters
- [ ] Delete the old `*.layout` files once the above are green

**4. Extensions unlocked by the rewrite**

- [ ] Port hard-coded exporters to templates (e.g. `logic.exporter.CffExporter`)
- [ ] Exporter for academicpages.github.io - [koppor/jabref#684](https://github.com/koppor/jabref/issues/684)
- [ ] Exporter for a Markdown static bibliography page - [koppor/jabref#468](https://github.com/koppor/jabref/issues/468)

**5. Documentation**

- [ ] Rewrite the custom export documentation at https://docs.jabref.org/collaborative-work/export/customexports

### Backwards compatibility

Two options, worth deciding early:

1. Convert everything up front with the CLI converter and drop the old format entirely.
2. Let users keep either format and run the converter transparently when a non-Thymeleaf template is processed.

### Minimal example

Target output: title, a note on whether the entry is from this century, keywords as bullets, and abstract + comments only when the abstract is under 30 characters. This is **not expressible** in the current engine - the century check would need a [Java formatter](https://docs.jabref.org/collaborative-work/export/customexports#custom-formatters), and the abstract-length dependency is impossible because formatters only receive a `String`.

Template (`resources/layout/thymeleaf.template`):

```
[(${entry.title})]
This is a document from [# th:text="${entry.year >= 2000} ? 'our' : 'another'"][/] century.
[# th:each="keyword : ${#strings.arraySplit(entry.keywords,', ')}"]
 - [(${keyword})]
[/]
[# th:if="${entry.abstract.length < 30}"]
 Abstract : [(${entry.abstract})]
 Comments : [(${entry.comment})]
[/]
```

Driver:

```java
ClassLoaderTemplateResolver templateResolver = new ClassLoaderTemplateResolver();
templateResolver.setPrefix("layout/");
templateResolver.setSuffix(".template");
templateResolver.setCharacterEncoding("UTF-8");
templateResolver.setTemplateMode("TEXT");

TemplateEngine templateEngine = new TemplateEngine();
templateEngine.setTemplateResolver(templateResolver);

Context context = new Context();
context.setVariables(Map.of("entry", Map.of(
    "title", "This is the title.",
    "abstract", "This is a short abstract.",
    "year", 2023,
    "keywords", "keyword1, keyword2, keyword3"
)));

System.out.println(templateEngine.process("thymeleaf", context));
```

Output:

```
This is the title.
This is a document from our century.
 - keyword1
 - keyword2
 - keyword3
Abstract : This is a short abstract.
Comments : This is a comment.
```

### Delivery approach

All work on a `thymeleaf_rewrite` branch. The branch merges into `main` at the end. **Everything should carry tests**.

**Comment by subhramit** [comment]
### On the OO/LO part (pasting from Claude):

On "Rewrite OpenOffice/LibreOffice integrations (`logic.openoffice.style`)" - that package is exactly where jstyle parsing and rendering lives.
The use-case paragraph links "LibreOffice/OpenOffice/MS Office" to the [style file docs](https://docs.jabref.org/cite/openofficeintegration#the-style-file), i.e. the jstyle reference page, and promises users "fine-grained control over the display of their bibliographic entries."

The technical reason this can't be dodged: a `.jstyle` file's `[layout]` section uses the same bracketed-pattern syntax the proposal is removing - `\format[Formatter]{\field}` runs through `LayoutHelper`/`LayoutEntry`. So "delete old `*.layout` files, rewrite the layout engine" necessarily changes how the layout half of jstyle is evaluated, whatever the proposal says about it.

What's left undefined is the scope of that change, and there are three quite different answers:

1. Keep the jstyle file format byte-identical, and only swap the internal renderer for the layout expressions (least disruptive, most existing user styles survive).
2. Keep the file but let the layout sections accept Thymeleaf syntax, with a converter for old ones - a breaking-ish change to a format lots of users have hand-written (We won't do this).

**Comment by subhramit** [comment]
It is completely fine to skip the OO/LO part for this, to avoid conflicts with legacy jstyles. Or we at least need to ensure 100% backward compatibility.

**Comment by subhramit** [comment]
ADR: https://devdocs.jabref.org/decisions/0039-use-apache-velocity-as-template-engine.html
