### ISSUE TITLE
Convert/rework rest of the Swing Dialogs to javafx 

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#3861]
This issue serves as point to see which dialogs need to be migrated and which need to be converted:
@JabRef/developers  please have a look at that list and see if I maybe missed some
Some of the dialogs are very easy to convert and could be nice beginner tasks 

- [x] Global Search Results (includes converting SearchWorker to JavaFX Tasks) 
- [x] SidePanel:  OpenOffice #4341 
- [x] SidePanel: WebSearch
- [x] Import->Append  Library Dialog
- [x] Import Inspection (assigned to @tobiasdiez #4692)
- [x] Connect to shared DB #4040 
- [x] Edit-> Manage Keywords
- [x] Edit-> Replace String #4227 (Thx to  @marisuki )
- [x] Edit-> Set/Clear/Append Rename Fields
- [x] Groups -> Add new Group #2630 
- [x] Groups -> Edit Group
- [x] Library-> New Entry Dialog #4312 
- [x] Library-> Edit Strings  #3735 
- [x] Library-> Library  properties #4617
- [x] Quality -> Find Duplicates (broken Threading due to PreviewPanel) #4601 
- [x] Quality -> Duplicate bibtex keys (Removed as part of #4696 )
- [x] Quality -> Merge Entries #4410 
- [x] Quality -> Cleanup Entries
- [x] Quality -> Find unlinked files
- [x] Tools ->New sublibrary from Aux file
- [x] Tools -> Writing XMP Data to Entry (Just a simple status? dialog)
- [x] Options -> Setup general fields #4346 (Thx to @NorwayMaple)
- [x] Options -> Manage custom imports
- [x] Options -> Manage custom exports
- [x] Options -> Manage external filetype 
- [x] Options -> Manage external filetype -> Edit file types  #4885
- [x] Options -> Manage protected Terms (add file is broken due to Threading)
- [x] Options -> Manage content Selectors  #4658 (Thx to @ricantech )
- [x] Options -> Customize entry types
- [x] Options -> Bibtex Key Patterns 
- [x]  *Push Entries to Application. Related to Options -> Preferences -> External Programs*
- [x] Review Changes dialog  #4693 
- [x] Import from plaintext
- [x] Merge shared entry dialog
- [x] Wait for save dialog #4697 

Still need to be converted to MVVM (not a beginner task):
- [ ] Options -> Preferences #4253

**Comment by LinusDietz** [comment]
This is an excellent opportunity for new developers to make a relatively easy first contribution.

**Comment by tobiasdiez** [comment]
Good to hear @jssander! The general aim is to convert these dialogs to the "new" UI technology JavaFX while at the same time improving the user experience/work flow. Do you already have experience with JavaFX? 
I think the "Find unlinked files" dialog is a good first project. The dialog is not too complex and reasonable well designed. Thus you can convert it more or less identically to JavaFX (Personally, I would move the "Select all/none" buttons below the file tree and remove the "expand/collapse" buttons). For code examples, have a look at the dialogs "Options > Manage journal abbreviations" or "Key bindings". And, of course, feel free to ask questions here or in gitter.

**Comment by gsweetwood** [comment]
Hey @tobiasdiez, I am new to this project but I'm learning JavaFX now and will start converting the dialogs.  I will also take a look at the placement of the buttons that you mentioned.

**Comment by tobiasdiez** [comment]
@gsweetwood Nice to hear that you are interested in contributing to JabRef! Since @jssander expressed interest in converting the "Find unlinked files" dialog and he already has some experience with the code of this dialog, it is probably best to leave this conversion to him (if you have not yet started).

But you are lucky and there are still a few others dialogs that needs attention. As a good start, I would recommend the three dialogs under "Edit" (with the "Manage keywords" being the most complicated of those).

**Comment by gsweetwood** [comment]
Great, thanks for the recommendation.  I'll start there.

**Comment by gsweetwood** [comment]
Hey @tobiasdiez, I noticed that the examples you gave ("Options > Manage journal abbreviations") have controller, view, and view model classes.  I'm working on  Edit-> Set/Clear/Append Rename Fields, which is currently handled with just one class.  Do you want me to create the classes like the example or to just modify the existing class?

**Comment by tobiasdiez** [comment]
@gsweetwood Yes, please use the new separation in view and view model (often called MVVM pattern). More details can be found in our wiki: https://github.com/JabRef/jabref/wiki/Code---JavaFX. In practice, you can still reuse most of the logic (as part of the view model class) but often need to rewrite most of the view/controller.

(And please base your code on the maintable-beta branch, there we made some major changes also to the structure - mainly merging the controller and the view). Thanks!

**Comment by ProgrammingBanana** [comment]
Hello this would be the first contribution I make to an open source project.  Is there something you'd suggest I do?  Im also starting working with JavaFx but have a pretty good understanding of Java

**Comment by Siedlerchr** [comment]
Hey, thanks for your interest. You could transform the manage protected terms dialog to JavaFX. You can create the layout with scene builder (the fxml). For some general information about dialogs with javafx have a look at our wiki. 
The easiest way is to look at existing javafx dialogs. 
Feel free to ask any questions, either in your PR then or in our gitter chat.

**Comment by Siedlerchr** [comment]
We have gone a long way and now the final last dialog to convert is Push to application the settings. This would be a great way to implement the  in https://github.com/JabRef/jabref/issues/674

#4719 however, is an extra issue as it depends on the new layout of the entry editor

**Comment by LinusDietz** [comment]
I have created a PR with some architecture tests to display, where Swing is still used. https://github.com/JabRef/jabref/pull/4894
