### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#4190]
- [ ] set general fields in background/no modal dialog
- [ ] manage custom imports no modal dialog
- [ ] manage custom exports no modal dialog
- [ ] manage content selectors no modal dialog
- [ ] customize entry types in background/no modal dialog
- [x] manage journal abbreviations cannot be closed by x button (fixed with #4263)
- [x] appearance tab inside preferences is empty (fixed with #4178)
![image](https://user-images.githubusercontent.com/2141507/42633619-5fc7479a-85e1-11e8-832b-f7edaa04aef0.png)
- [x] checkboxes are not recognizable for user (appearance tab) (fixed with #4261)
![image](https://user-images.githubusercontent.com/2141507/42727853-243d3ff8-87ae-11e8-83a7-320b5bcaa30a.png)

**Comment by mlep** [comment]
I believe that "appearance tab inside preferences is empty" is still not solved yet: while, indeed, the appearance tab is not empty anymore, only the font size can be selected (thanks to #4178). But the Look&Feel cannot be chosen yet. And once the Look&Feel could be set int the appearance tab, issue #4197 will be solved.

**Comment by stefan-kolb** [comment]
There is no look and feel anymore.

**Comment by mlep** [comment]
Thank you for the clarification. It was not clear to me from the discussion on issue #4197.

**Comment by Siedlerchr** [comment]
As we are migrating the rest of the dialogs to javafx, the old look and feel settings become obsolete as they only affect the old swing dialogs See also  #4130 were we try to provide a dark theme for javafx.
As it's solely based on css new themes can easily be developed

**Comment by mlep** [comment]
So, the "Freezes when "Add to Group"" bug (issue #4197) will "naturally" be solved thanks to this migration. Great!

**Comment by tobiasdiez** [comment]
There is nothing we can do about the modality of the old Swing dialogs as that would need a main Swing window. Since the other issues are now fixed, I'll this now.
